'use client';
import { Bid } from '@/lib/api';
function fp(p: number | null | undefined) { if (p == null) return 'N/A'; return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', minimumFractionDigits: 2 }).format(typeof p === 'number' ? p : parseFloat(String(p))); }
function fd(s: string) { return new Date(s).toLocaleDateString('en-US', { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }); }
export default function BidHistorySection({ bids }: { bids: Bid[] }) {
  const sorted = [...bids].sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());
  const top = sorted[0];
  return (
    <div className="rounded-xl border border-gray-200 bg-white p-6">
      <div className="flex items-center justify-between"><h3 className="text-lg font-semibold text-gray-900">Bid History</h3><span className="rounded-full bg-gray-100 px-3 py-1 text-xs font-medium text-gray-600">{bids.length} {bids.length === 1 ? 'bid' : 'bids'}</span></div>
      {top && <div className="mt-4 rounded-lg border border-green-200 bg-green-50 p-4"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="h-5 w-5 text-green-600"><path d="m5 12 7-7 7 7" /><path d="M12 19V5" /></svg><span className="text-sm font-medium text-green-800">Highest Bid</span></div><span className="text-lg font-bold text-green-700">{fp(top.amount)}</span></div><p className="mt-1 text-xs text-green-600">Placed {fd(top.createdAt)}</p></div>}
      {bids.length > 0 ? (<div className="mt-6 overflow-hidden rounded-xl border border-gray-200"><table className="w-full text-sm"><thead><tr className="border-b border-gray-200 bg-gray-50"><th className="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Bidder</th><th className="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Amount</th><th className="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Time</th><th className="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Status</th></tr></thead><tbody>{sorted.map((b, i) => (<tr key={b.id} className={`${i === 0 ? 'bg-green-50/50' : i % 2 === 0 ? 'bg-gray-50' : 'bg-white'} ${i < sorted.length - 1 ? 'border-b border-gray-100' : ''}`}><td className="px-4 py-3"><div className="flex items-center gap-2"><div className="flex h-7 w-7 items-center justify-center rounded-full bg-gradient-to-br from-blue-400 to-violet-500 text-xs font-bold text-white">{b.bidderId.slice(0, 1).toUpperCase()}</div><span className="font-medium text-gray-700">User {b.bidderId.slice(0, 6)}</span></div></td><td className="px-4 py-3 font-semibold">{fp(b.amount)}</td><td className="px-4 py-3 text-gray-500">{fd(b.createdAt)}</td><td className="px-4 py-3">{b.isWinning ? <span className="rounded-full bg-green-100 px-2 py-0.5 text-xs font-medium text-green-700">Leading</span> : <span className="rounded-full bg-gray-100 px-2 py-0.5 text-xs font-medium text-gray-500">Outbid</span>}</td></tr>))}</tbody></table></div>) : (<div className="mt-6 rounded-lg border border-dashed border-gray-300 bg-gray-50 p-8 text-center"><p className="text-sm font-medium text-gray-500">No bids yet</p><p className="mt-1 text-xs text-gray-400">Be the first to bid!</p></div>)}
    </div>
  );
}
